### PR TITLE
Publish

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 64 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-535ff5910/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 65 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-db5fa1769/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 66 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-c3d3f7f67/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 67 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d22c3d2fb/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 68 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-782549d9a/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 69 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ac88cb130/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 70 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-996658310/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 71 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-776d5e02c/docs/docs-colocation-guide/). valid for 14 days

**Comment by WilliamLoy** [comment]
@catlook this puppy is ready for some edits :)

**Comment by catlook** [comment]
@WilliamLoy, I edited all the files in this PR. Review my edits and see if you agree!

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 83 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2eb1f3ac9/docs/docs-colocation-guide/). valid for 14 days

**Pull request merged**
