### PR TITLE
New content

### PR DESCRIPTION
**Pull request by WilliamLoy**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 43 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-7c3fa2fce/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 44 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3580833e2/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 45 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b35702b53/docs/docs-colocation-guide/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 47 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b58780506/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 48 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-df89e2d32/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 49 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bd36a10ea/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 50 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0d1e4ef12/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 51 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b0977350b/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 52 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-4253d0fe1/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 53 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3c5dcd5e7/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 54 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-338658d4b/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 55 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f6ce3af31/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 56 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-616372d23/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 57 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-f91f23f38/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 58 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b65b31bed/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 59 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-e141a357e/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 60 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ca97b6b88/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 61 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-3581c8cfb/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 62 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-be6d0998e/docs/docs-colocation-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 63 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-40bd7cf9b/docs/docs-colocation-guide/). valid for 14 days

**Pull request merged**
